name: Qodana
on:
  workflow_dispatch:
jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana
      - uses: actions/download-artifact@v2
        id: download
        with:
          path: qodana
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
